import { ArrowUpRight } from 'lucide-react'
import { motion } from 'framer-motion'
import { Reveal } from '../components/Reveal'
import { SectionHeading } from '../components/SectionHeading'
import { galleryImages } from '../data/content'

const galleryMotion = [
  { initial: { opacity: 0, x: -36 }, whileInView: { opacity: 1, x: 0 } },
  { initial: { opacity: 0, y: 36, rotate: -4 }, whileInView: { opacity: 1, y: 0, rotate: 0 } },
  { initial: { opacity: 0, scale: .82 }, whileInView: { opacity: 1, scale: 1 } },
  { initial: { opacity: 0, x: 36, rotate: 4 }, whileInView: { opacity: 1, x: 0, rotate: 0 } },
]

export function GallerySection() {
  return <section id="gallery" className="section-pad overflow-hidden bg-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><SectionHeading eyebrow="Life at YEA" title="A little look at big days." text="From first discoveries to muddy-kneed adventures, these are the moments that make learning feel alive." action="Come see us" /></Reveal><div className="mb-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#e6edf2] bg-[#f8fbff] p-4"><span className="text-2xl">01</span><p className="mt-2 text-xs font-bold text-slate-500">Celebrate milestones</p></div><div className="rounded-2xl border border-[#e6edf2] bg-[#fffaf4] p-4"><span className="text-2xl">02</span><p className="mt-2 text-xs font-bold text-slate-500">Explore our culture</p></div><div className="rounded-2xl border border-[#e6edf2] bg-[#f4fbf5] p-4"><span className="text-2xl">03</span><p className="mt-2 text-xs font-bold text-slate-500">Learn by doing</p></div></div><div className="grid auto-rows-[170px] grid-cols-2 gap-3 sm:auto-rows-[190px] sm:grid-cols-4 sm:gap-4">{galleryImages.map((item, index) => { const animation = galleryMotion[index % galleryMotion.length]; return <Reveal key={item.image} delay={(index % 6) * .06} y={0}><motion.figure initial={animation.initial} whileInView={animation.whileInView} viewport={{ once: true, amount: .2 }} transition={{ duration: .65, ease: [.22, 1, .36, 1] }} drag dragConstraints={{ top: -18, bottom: 18, left: -18, right: 18 }} dragElastic={.2} whileTap={{ scale: .98, cursor: 'grabbing' }} whileHover={{ y: -8, rotate: index % 2 === 0 ? -1.2 : 1.2 }} className={`group relative h-full cursor-grab overflow-hidden rounded-[24px] bg-[#1f78b9] shadow-sm transition-shadow hover:shadow-xl ${index === 0 ? 'col-span-2 row-span-2' : index === 3 ? 'row-span-2' : ''}`}><img src={item.image} alt={item.alt} className="h-full w-full object-cover transition duration-700 ease-out group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#17324d]/80 via-transparent to-transparent opacity-70 transition group-hover:opacity-90"/><figcaption className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-3 text-white"><span><span className="mb-1 block text-[9px] font-black uppercase tracking-[.18em] text-[#ffd00a]">{'event' in item ? item.event : 'Young Explorers'}</span><span className="max-w-[16rem] font-display text-sm font-black leading-tight sm:text-base">{item.label}</span></span><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#ffd00a] text-[#17324d] opacity-0 transition duration-300 group-hover:opacity-100"><ArrowUpRight size={16}/></span></figcaption></motion.figure></Reveal> })}</div></div></section>
}