import { motion } from 'framer-motion'
import { ArrowUpRight } from 'lucide-react'
import { programs } from '../data/content'
import { Reveal } from '../components/Reveal'
import { SectionHeading } from '../components/SectionHeading'

export function ProgramsSection() {
  return <section id="programs" className="section-pad bg-[#fffaf4] relative overflow-hidden"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><SectionHeading eyebrow="Our programs" title="Fun & engaging classes for every stage of early learning." text="Purposeful activities, friendly teachers and lots of room for children to learn at their own pace." action="View all programs" /></Reveal><div className="grid gap-5 md:grid-cols-2">{programs.map((program, i) => <Reveal key={program.title} delay={i*.08}><motion.article whileHover={{y:-7}} className="group overflow-hidden rounded-[28px] border border-[#202c4b]/10 bg-white shadow-sm"><div className="grid sm:grid-cols-[.9fr_1.1fr]"><div className="h-56 overflow-hidden sm:h-full"><img src={program.image} alt={program.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[#ffcf58]/30 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#202c4b]">{program.age}</span><ArrowUpRight size={20} className="text-[#ff756f] transition group-hover:translate-x-1 group-hover:-translate-y-1" /></div><h3 className="mt-7 font-display text-2xl font-black text-[#202c4b]">{program.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{program.description}</p><a href="#contact" className="mt-6 inline-block text-xs font-black uppercase tracking-wider text-[#ff756f]">Learn more</a></div></div></motion.article></Reveal>)}</div></div></section>
}
